### ISSUE TITLE
Can local tarballs be used for push?

### ISSUE THREAD

**Issue by bastianbeier** [estesp/manifest-tool#154]
Hello,
I would like to use manifest-tool to build a multi-arch image from two tarballs that i have only locally.
Is this possible? It would be great if I don't need to push them first to "merge" them. I didn't find any documentation on that. Usecase would be CICD for this.
e.g 
```
image: myprivreg:5000/someimage:latest
manifests:
  -
    image: dir:localarmimage
    platform:
      architecture: arm64
      os: linux
 -
    image: dir:localamdimage
    platform:
      architecture: amd64
      os: linux
```
Thank you in advance!
Greetings Basti
