### ISSUE TITLE
Image doesnt include docker-credential-ecr-login for AWS credential helper

### ISSUE THREAD

**Issue by olivermussell** [estesp/manifest-tool#192]
I’m running a Gitlab CI runner instance on Kubernetes (EKS) in AWS, and using an IRSA for authentication/permissions. manifest-tool is run in the pipeline once the multiple architecture images are created and pushed to the container registry (ECR). But when running manifest-tool to push the final manifest it was producing this error:

```
time=“2022-11-30T13:22:04Z” level=fatal msg=“Inspect of image \“$my_aws_account_id.dkr.ecr.us-east-1.amazonaws.com/$my_image_name:$my_tag_name-amd64\” failed with error: error getting credentials - err: exec: \“docker-credential-ecr-login\“: executable file not found in $PATH, out: ``”
```

Which appears to be fixed by installing the `docker-credential-ecr-login`  package in the alpine container prior to running the manifest-tool binary. I'm unsure if its correct to be installing this package or if there is something else required for it to pick up the credentials correctly.

For context, here’s how its run in the gitlab-ci.yml:

```
multi_arch_manifest:
  stage: build_multi_arch_image
  variables:
    AWS_SDK_LOAD_CONFIG: “true”
    AWS_EC2_METADATA_DISABLED: “true”
  tags:
    - eks
    - amd64
  needs: [“build_image_amd64", “build_image_arm64”]
  image: mplatform/manifest-tool:alpine
  script:
  - echo ‘{“credsStore”:“ecr-login”}’ > /config.json
  - apk add docker-credential-ecr-login                       <---- This fixes this issue
  - manifest-tool --docker-cfg /config.json push from-args
    --platforms linux/amd64,linux/arm64
    --template “$my_aws_account_id.dkr.ecr.us-east-1.amazonaws.com/$my_image_name:$my_tag_name-ARCHVARIANT”
    --target “$my_aws_account_id.dkr.ecr.us-east-1.amazonaws.com/$my_image_name:multiarch”
```
