### ISSUE TITLE
multiple tags in a single yml file

### ISSUE THREAD

**Issue by glennc** [estesp/manifest-tool#23]
In a single repo I want to setup multiple tags pointing to the same few base images. Something like this:

```yml
image: glennc/dotnet:1.1-runtime
manifests:
  -
    image: microsoft/dotnet:1.1.0-runtime
    platform:
      architecture: amd64
      os: linux
  -
    image: glennc/dotnet:1.1.0-runtime-nanoserver
    platform:
      architecture: amd64
      os: windows
image: glennc/dotnet:1.1-sdk
manifests:
  -
    image: glennc/dotnet:1.1.0-sdk-msbuild-rc4
    platform:
      architecture: amd64
      os: linux
  -
    image: glennc/dotnet:1.1.0-sdk-msbuild-rc4-nanoserver
    platform:
      architecture: amd64
      os: windows
```
Is there a YAML format I am missing that would make this possible? Seems like I would need many different files to make it work right now.  If there is no good way to do it I could propose some formats we would accept and do a PR. Though my Go skills are weak so it might be a painful PR process to begin with :).
