### ISSUE TITLE
incorrect manifest reference push URL

### ISSUE THREAD

**Issue by yamag104** [estesp/manifest-tool#33]
Hello,

I am having trouble pushing my manifest list to my private registry.
Let's say my server was https://docker.test.com/v1/

I am getting the following error. The debug output shows that the reference push URL is appended twice (docker.test.com after docker.test.com).

```
DEBU[0005] manifest reference push URL: https://docker.test.com/v1/docker.test.com/v1/repo-name/manifests/shaxxx:xxxxxxxxx
FATA[0005] Couldn't push manifests referenced in our manifest list: Referenced manifest push unsuccessful: response 400: 400 Bad Request 
```

This is the command I use to run this:
`./manifest-tool --debug --docker-cfg '/home/user/.docker/' push from-spec <path-to-yaml>`

My config.json file looks like this:
```
{
	"auths": {
		"docker.test.com": {
			"auth": "xxxxxxxxxxxxxx"
		}
	}
}
```

this is what my yaml file looks like
```
image: docker.test.com/v1/repo-name:6
manifests:
  -
    image: docker.test.com/v1/repo-name-arm:1.0
    platform:
      architecture: arm
      os: linux
  -
    image: docker.test.com/v1/repo-name-x86/1.0:latest
    platform:
      architecture: amd64
      os: linux
```

Please let me know how I can resolve this. Thanks.

**Comment by estesp** [comment]
Hi! Thanks for the report. I've tested the hostname/reponame code with your example just to verify there isn't an edge case that I haven't caught yet. All seems to be working fine and no duplication of reponame with the hostname.

Maybe your real use case is slightly different than the "docker.test.com" example above? Can you share with me the full debug output or provide the exact repo names in case there is a bug with the hostname/reponame parsing code? If you need to do it in private feel free to send an email. Thanks!

**Comment by yamag104** [comment]
Hi!
This represents my use case better: docker4.foo.test.com
Please let me know if you can repro this.
```
image: docker4.foo.test.com/v1/repo-name:6
manifests:
  -
    image: docker4.foo.test.com/v1/repo-name-arm:1.0
    platform:
      architecture: arm
      os: linux
  -
    image: docker4.foo.test.com/v1/repo-name-x86/1.0:latest
    platform:
      architecture: amd64
      os: linux
```
