### ISSUE TITLE
Should I re-push manifest each time I update my image ? 

### ISSUE THREAD

**Issue by CocoaWang** [estesp/manifest-tool#64]
I am building multi-arch images across s390x and amd64.
 Say I have a image manifest like 
```
image: swangbj/gosdk:latest
tags: ['latest']
manifests:
  -
    image: swangbj/gosdk:s390x-latest
    platform:
      architecture: s390x
      os: linux
  -
    image: swangbj/gosdk:amd64-latest
    platform:
      architecture: amd64
      os: linux
```
And I pushed the manifest file and the images `swangbj/gosdk:s390x-latest` and `swangbj/gosdk:amd64-latest` to the docker hub. After that , I can pull images in different architecture with same tag `swangbj/gosdk:latest`.
But after I pushed the new image `swangbj/gosdk:s390x-latest`,it seems I can't get the updated image by using `swangbj/gosdk:latest`.It always give me the old one .
