### ISSUE TITLE
Manifest-Lists needs to have the same repo-name

### ISSUE THREAD

**Issue by ChristianKniep** [estesp/manifest-tool#66]
I am exploring it in the context of having images for accelerators or optimized for a certain CPU and I would like to clarify how this works.

Say I have this YAML
```
image: qnib/ffmpeg:latest-rev8
manifests:
  -
    image: qnib/uplain-ffmpeg:latest-rev2
    platform:
      architecture: amd64
      os: linux
  -
    image: qnib/uplain-cuda-ffmpeg:9.2-rev2
    platform:
      architecture: amd64
      os: linux
      features:
        - cuda9.2
  -
    image: qnib/uplain-cuda-ffmpeg:10.0-rev2
    platform:
      architecture: amd64
      os: linux
      features:
        - cuda10.0
```
I do a `push` and it works fine. Looking at the spec I was afraid that the image had to have the same base name since the manifest list definition only specifies digests referencing to the same name.
https://docs.docker.com/registry/spec/manifest-v2-2/#example-manifest-list

But that does not matter, does it? When pushing to my private registry (DTR 2.6.0) I can see a new set of images are pushed to the resulting images (even though they are already there).

Question is: The manifest-tool is pulling and pushing the images in the process?
